cc_library(
    name = "apue_send_recv_fd",
    srcs = [
        "apue.h",
        "error.c",
        "recvfd.c",
        "senderr.c",
        "sendfd.c",
    ],
    defines = [
        "_GNU_SOURCE",
    ],
    visibility = ["//visibility:public"],
)
